name: 'dema_dbt'

version: "1.0.0"
config-version: 2

profile: 'dema_dbt'

analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  dema_dbt:
    +materialized: "table"