dema_dbt:
  target: prod
  outputs:
    prod:
      type: postgres
      host: "{{ env_var('DAGSTER_POSTGRES_HOST') }}"
      user: "{{ env_var('DAGSTER_POSTGRES_USER') }}"
      password: "{{ env_var('DAGSTER_POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('DAGSTER_POSTGRES_DB') }}"
      schema: public
      threads: 4
      keepalives_idle: 0